export { default as Account } from './Account';
export { default as Dashboard } from './Dashboard';
export { default as NotFound } from './NotFound';
export { default as MyTask } from './MyTask';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as UserList } from './UserList';
export { default as Notification } from './Notification';
export { default as About } from './About';
